constants:
  root_url: <%= ENV['OW_ROOT_URL']%>

  cloudfront:
    domain: <%= ENV['OW_CLOUDFRONT_DOMAIN'] %>

  basic_auth:
    username: <%= ENV['OW_BASIC_AUTH_USERNAME'] %>
    password: <%= ENV['OW_BASIC_AUTH_PASSWORD'] %>

  memcached:
    instances: <%= ENV['OW_MEMCACHED_INSTANCES'] %>

  cms:
    url: <%= ENV['STW_CMS_URL'] %>
    sha256_salt: <%= ENV['STW_CMS_SHA256_SALT'] %>

  company_other_product_urls:
    kyc_root_url: <%= ENV['COMPANY_KYC_ROOT_URL'] %>
    kit_root_url: <%= ENV['COMPANY_KIT_ROOT_URL'] %>
    view_root_url: <%= ENV['COMPANY_VIEW_ROOT_URL'] %>
    token_sale_url: <%= ENV['COMPANY_TOKEN_SALE_URL'] %>
    simple_token_url: <%= ENV['COMPANY_SIMPLE_TOKEN_URL'] %>
    dev_ost_root_url: <%= ENV['COMPANY_DEV_ROOT_URL'] %>
    android_demo_app_download_url: <%= ENV['COMPANY_ANDROID_DEMO_APP_DOWNLOAD_URL'] %>
    ios_demo_app_download_url: <%= ENV['COMPANY_IOS_DEMO_APP_DOWNLOAD_URL'] %>

  pepo_campaign:
    encrypted_client_id: <%= ENV['STW_CAMPAIGN_ENCRYPTED_CLIENT_ID'] %>
    encrypted_list_id: <%= ENV['STW_CAMPAIGN_ENCRYPTED_LIST_ID'] %>

  recaptcha:
    site_key: <%= ENV['OST_RECAPTCHA_SITE_KEY'] %>

  placeholder_image_src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAABGdBTUEAALGPC/xhBQAAABdJREFUCB1j/PTp038GJMCExAYzCQsAAPxAA91ZSr1IAAAAAElFTkSuQmCC"